"""add event_id and base_event_id and indexing

Revision ID: 59a1e8af7ca1
Revises: 462fea73a25f
Create Date: 2024-04-19 16:20:44.608781

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "59a1e8af7ca1"
down_revision: Union[str, None] = "462fea73a25f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("event_id", sa.Integer(), nullable=False))
    op.add_column("events", sa.Column("base_event_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_events_base_event_id"), "events", ["base_event_id"], unique=False)
    op.create_index(op.f("ix_events_end_date_time"), "events", ["end_date_time"], unique=False)
    op.create_index(op.f("ix_events_event_id"), "events", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_events_start_date_time"), "events", ["start_date_time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_start_date_time"), table_name="events")
    op.drop_index(op.f("ix_events_event_id"), table_name="events")
    op.drop_index(op.f("ix_events_end_date_time"), table_name="events")
    op.drop_index(op.f("ix_events_base_event_id"), table_name="events")
    op.drop_column("events", "base_event_id")
    op.drop_column("events", "event_id")
    # ### end Alembic commands ###
